name: build-and-test

run-name: Test by @${{ github.actor }}

on:
  push:
    branches: [master]

  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Setup
        run: |
          go install gotest.tools/gotestsum@v1.11.0
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.6
          working-directory: .
          args: -v --timeout=10m
      - name: Build
        run: go build ./...
      - name: Run tests
        run: go test ./...
      - name: Test
        run: gotestsum --jsonfile tmp/test-results.json -- -timeout 20m ./...
      - name: Annotate tests
        uses: guyarb/golang-test-annotations@v0.8.0
        if: success() || failure() # always run even if the previous step fails
        with:
          test-results: tmp/test-results.json
